[project]
name = "py4pd-mypackage"
version = "0.1.0"
description = "Description."
dependencies = [
    "numpy",
]

[project.urls]
"Source Code" = "https://github.com/username/package" 

[tool.setuptools]
packages = ["mypackage"] 
