name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install PureData
      run: brew install --cask pd

    - name: search for PureData bin and export VAR
      run: ls /Applications/Pd-0.53-1.app/Contents/Resources/bin/


    - name: Build
      run: make PYTHON_VERSION=python3.11 PYTHON_INCLUDE=/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11

    - name: Upload Object
      uses: actions/upload-artifact@v2
      with:
        name: py4pd
        path: py4pd.pd_darwin 

    - name: Move py4pd.pd_darwin to test
      run: mv py4pd.pd_darwin test/py4pd.pd_darwin

    - name: Run Test
      run: pd -nogui test.pd
    