name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  # macos-universal-build:
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: recursive
  #       fetch-depth: 0

  #   - name: Install PureData
  #     run: brew install --cask pd

  #   - name: Build
  #     run: make PYTHON_VERSION=python3.11 PYTHON_INCLUDE=/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11

  #   - name: Upload Object
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: py4pd
  #       path: py4pd.pd_darwin 

  #   - name: Move py4pd.pd_darwin to test
  #     run: mv py4pd.pd_darwin test/py4pd.pd_darwin

  #   - name: Run Test
  #     run: /Applications/Pd-*.app/Contents/Resources/bin/pd -nogui test/test.pd

# run on Windows
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: check where python is
      run: where python

    # - if: runner.os == 'Windows'
    #   name: "Install mingw deps"
    #   uses: msys2/setup-msys2@v2
    #   with:
    #       install: make autoconf automake libtool mingw-w64-x86_64-gcc libtool mingw-w64-x86_64-libwinpthread-git
    #       update: false

    
    # - if: runner.os == 'Windows'
    #   shell: msys2 {0}
    #   run: make PYTHON_INCLUDE="~/AppData/Local/Programs/Python/Python311/include" PYTHON_DLL="~/AppData/Local/Programs/Python/Python311/python311.dll"
    
    
    # - name: Install PureData
    #   run: choco install puredata --yes

    # - name: Install Python 3.11
    #   run: choco install python --version 3.11.0 --yes

    # - name: Build
    #   run: make PYTHON_INCLUDE="~/AppData/Local/Programs/Python/Python311/include" PYTHON_DLL="~/AppData/Local/Programs/Python/Python311/python311.dll"

    # - name: Rename py4pd.dll to py4pd.m_amd64
    #   run: mv py4pd.dll py4pd.m_amd64

    # - name: Upload Object
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: py4pd
    #     path: py4pd.m_amd64

    # - name: Upload Python DLL
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: py4pd
    #     path: ~/AppData/Local/Programs/Python/Python311/python311.dll





    