name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install PureData
      run: brew install --cask pd

    - name: Build
      run: make PYTHON_VERSION=python3.11 PYTHON_INCLUDE=/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11

    - name: Create py4pd_macOS-Intel
      run: mkdir py4pd_macOS-Intel

    - name: Copy files to py4pd_macOS-Intel
      run: cp py4pd.pd_darwin py4pd.cfg py.py py4pd-help.pd py4pd_macOS-Intel

    - name: Zip py4pd_macOS-Intel
      run: zip -r py4pd_macOS-Intel.zip py4pd_macOS-Intel

    - name: Upload Object
      uses: actions/upload-artifact@v3
      with:
        name: py4pd_macOS-Intel
        path: py4pd_macOS-Intel.zip

    - name: Move py4pd.pd_darwin to test
      run: mv py4pd.pd_darwin test/py4pd.pd_darwin

    - name: Run Test
      run: mv py4pd.pd_darwin test/py4pd.pd_darwin && /Applications/Pd-*.app/Contents/Resources/bin/pd -nogui test/test.pd

# # run on Windows
#   windows-build:
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         submodules: recursive
#         fetch-depth: 0

#     - uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'

#     - if: runner.os == 'Windows'
#       name: "Install mingw deps"
#       uses: msys2/setup-msys2@v2
#       with:
#           install: make autoconf automake libtool mingw-w64-x86_64-gcc libtool mingw-w64-x86_64-libwinpthread-git
#           update: false

#     - name: Create py4pd_WIN64
#       run: mkdir py4pd_WIN64
    
#     - name: Install PureData
#       run: choco install puredata --yes

#     - if: runner.os == 'Windows'
#       name: Build py4pd
#       shell: msys2 {0}
#       run: make PYTHON_INCLUDE="C:/hostedtoolcache/windows/Python/3.11.1/x64/Include/" PYTHON_DLL="C:/hostedtoolcache/windows/Python/3.11.1/x64/python311.dll"
    
#     - name: Rename py4pd.dll to py4pd.m_amd64
#       run: mv py4pd.dll py4pd.m_amd64

#     - name: Copy Lib Files
#       run: xcopy /s C:\hostedtoolcache\windows\Python\3.11.1\x64\Lib py4pd_WIN64\Python\Lib\

#     - name: Copy Dlls Files
#       run: xcopy /s C:\hostedtoolcache\windows\Python\3.11.1\x64\DLLs py4pd_WIN64\Python\DLLs\

#     - name: Move files to py4pd_WIN64
#       run: |
#           cp py4pd.m_amd64 py4pd_WIN64\
#           cp py4pd.cfg py4pd_WIN64\
#           cp py.py py4pd_WIN64\ 
#           cp python311._pth py4pd_WIN64\ 
#           cp py4pd-help.pd py4pd_WIN64\ 
#           cp C:\hostedtoolcache\windows\Python\3.11.1\x64\python311.dll py4pd_WIN64\
        
#     - name: zip py4pd_WIN64
#       run: 7z a py4pd_WIN64.zip py4pd_WIN64

#     - name: Move test.pd to py4pd_WIN64
#       run: cp test/test.pd py4pd_WIN64/test.pd

#     - name: Run Test
#       run: cmd /c "C:\Program Files\Pd\bin\pd.exe" -nogui py4pd_WIN64\test.pd

#     - name: Upload Object ZIP
#       uses: actions/upload-artifact@v3
#       with:
#         name: py4pd_WIN64
#         path: py4pd_WIN64.zip






    