name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    # - name: Clone PureData
    #   run: git clone https://github.com/puredata/pure-data.git
  

    - name: Print Python3.11 includes
      run: python3.11-config --includes

    # - name: Build
    #   run: make PDINCLUDEDIR=pure-data/src PYTHON_VERSION=python3.11 PYTHON_INCLUDE=u


      
