# name: C/C++ CI

on:
  push:
    branches: [ "master" , "v-0.5.0" ]
  pull_request:
    branches: [ "master" ]
  
jobs:

# # # # ===============================================================================================
# # # # ===============================================================================================
# # # # ===============================================================================================
  # macos-intel-build:
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: recursive
  #       fetch-depth: 0

  #   - name: Install PureData
  #     run: brew install --cask pd

  #   - name: Build
  #     run: make PYTHON_VERSION=python3.11 

  #   - name: Create py4pd_macOS-Intel
  #     run: mkdir py4pd_macOS-Intel

  #   - name: Copy files to py4pd_macOS-Intel
  #     run: cp py4pd.pd_darwin test/test.pd py4pd.cfg py.py py4pd-help.pd py4pd_macOS-Intel

  #   - name: Zip py4pd_macOS-Intel
  #     run: zip -r py4pd_macOS-Intel.zip py4pd_macOS-Intel

  #   - name: Upload Object
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: py4pd_macOS-Intel
  #       path: py4pd_macOS-Intel.zip

  #   - name: Set Test Config
  #     run: |
  #         cp test/test.py test.py
  #         python3.11 -m pip install neoscore -t ./py4pd_macOS-Intel/py-modules

  #   - name: Run Test
  #     run: python3.11 -c 'import test; test.runTest()' 

  #   - name: Upload Test Image
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: neoscore-Test-Mac
  #       path: py4pd_macOS-Intel/neoscoretest.png

# # # # ===============================================================================================
# # # # ===============================================================================================
# # # # ===============================================================================================
# run on Windows
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - if: runner.os == 'Windows'
      name: "Install mingw deps"
      uses: msys2/setup-msys2@v2
      with:
          install: make autoconf automake libtool mingw-w64-x86_64-gcc libtool mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-libsystre
          update: false

    - name: Create py4pd_WIN64
      run: mkdir py4pd_WIN64
    
    - name: Install PureData
      run: choco install puredata --yes

    - name: Get Python Paths
      # python -c "import os; import sys; print(os.path.dirname(sys.executable))" > 'pythonpath.txt'
      run: |
        python -c "import sysconfig; f = open('pythonincludes.txt', 'w'); print(sysconfig.get_paths()['include'].replace('\\', '/'), file=f); f.close()"
        python -c "import os; import sys; f = open('pythonpath.txt', 'w'); print(os.path.dirname(sys.executable).replace('\\', '/'), file=f); f.close()"
    
    - if: runner.os == 'Windows'
      name: Build py4pd
      shell: msys2 {0}
      run: |
        make PYTHON_VERSION=python3.11
        dll_path=$(where libsystre-0.dll)
        cp $dll_path .
    
    - name: Copy Files
      run: | 
        mv py4pd.dll py4pd.m_amd64
        $pythonpath = Get-Content pythonpath.txt
        xcopy /s $pythonpath/Lib py4pd_WIN64/Python/Lib/
        xcopy /s $pythonpath/DLLs py4pd_WIN64/Python/DLLs/
        xcopy /s $pythonpath/python311.dll py4pd_WIN64/python311.dll/

    - name: Move files to py4pd_WIN64
      run: |
          cp py4pd.m_amd64 py4pd_WIN64\
          cp py4pd.cfg py4pd_WIN64\
          cp py.py py4pd_WIN64\ 
          cp python311._pth py4pd_WIN64\ 
          cp py4pd-help.pd py4pd_WIN64\ 
          cp libsystre-0.dll py4pd_WIN64\
        
    - name: zip py4pd_WIN64
      run: 7z a py4pd_WIN64.zip py4pd_WIN64

    - name: Move test.pd to py4pd_WIN64
      run: cp test/test.pd py4pd_WIN64/test.pd

    
    - name: Set Test Config
      run: |
          cp test/test.py test.py
          python3 -m pip install neoscore -t ./py4pd_WIN64/py-modules
    
    - name: Run Test
      run: python3 -c 'import test; test.runTest()' 
      
    - name: Upload Test Image
      uses: actions/upload-artifact@v3
      with:
        name: neoscore-Test-Windows
        path: py4pd_WIN64/neoscoretest.png

    - name: Upload Object ZIP
      uses: actions/upload-artifact@v3
      with:
        name: py4pd_WIN64
        path: py4pd_WIN64.zip

# # # ===============================================================================================
# # # ===============================================================================================
# # # ===============================================================================================

# build for Linux
  # linux-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: recursive
  #       fetch-depth: 0

  #   - uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.11'

  #   - name: Install PureData
  #     run: sudo apt-get install puredata -y
    
  #   - name: Install Python-Devel
  #     run: sudo apt-get install python3.11-dev -y

  #   - name: Build
  #     # get python includes
  #     run: |
  #       make PYTHON_VERSION=python3.11 

  #   - name: Create py4pd_Linux
  #     run: mkdir py4pd_Linux

  #   - name: Copy files to py4pd_Linux
  #     run: cp py4pd.pd_linux test/test.pd py4pd.cfg py.py py4pd-help.pd py4pd_Linux

  #   - name: Zip py4pd_Linux
  #     run: zip -r py4pd_Linux.zip py4pd_Linux

  #   - name: Upload Object
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: py4pd_Linux
  #       path: py4pd_Linux.zip

  #   - name: Set Test Config
  #     run: |
  #         cp test/test.py test.py
  #         python3.11 -m pip install neoscore -t ./py4pd_Linux/py-modules
    
  #   - name: Run Test
  #     run: python3.11 -c 'import test; test.runTest()'

  #   - name: Upload Test Image
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: neoscore-Test-linux
  #       path: py4pd_Linux/neoscoretest.png




    
