name: Linux
'on':
  push:
    branches:
      - master
      - develop

    paths:
      - src/**
      - .github/workflows/Linux.yml
      - test/runTests.py

  pull_request:
    branches:
      - develop

    paths:
      - src/**
      - .github/workflows/Linux.yml

jobs:
  linux-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Build Dependencies
        # add Python 3.10-dev to the list of dependencies
        run: |
          sudo apt-get install puredata -y
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install python3.10-dev -y
          python3.10 -m pip install numpy

      - name: Build
        run: make PYTHON_VERSION=python3.10 extension=l_amd64
      
      - name: Copy files to py4pd
        run: |
          mkdir py4pd
          cp py4pd.l_amd64 resources/py4pd.cfg resources/py.py resources/py4pd-help.pd py4pd
          mkdir py4pd/resources
          mkdir py4pd/src
          cp resources/* py4pd/resources -r
          cp src/* py4pd/resources -r
          ./resources/localdeps/localdeps.linux.sh py4pd/py4pd.l_amd64
          zip -r py4pd.zip py4pd
          cp test/*.pd py4pd
          
          
      - name: Upload Object
        uses: actions/upload-artifact@v3
        with:
          name: py4pd-linux
          path: py4pd.zip

      - name: Set Test Config
        run: |
          cp test/runTests.py runTests.py
          python3.10 -m pip install neoscore matplotlib Pillow -t ./py4pd/py-modules

      - name: Run Test
        run: python3.10 runTests.py

      - name: Upload Test Image
        uses: actions/upload-artifact@v3
        with:
          name: neoscore-Test-linux
          path: py4pd/neoscoretest.png

