name: Linux
'on':
  push:
    branches:
      - master
      - v-0.5.0
      - develop

    paths:
      - src/**
      - .github/workflows/Linux.yml
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/Linux.yml
  workflow_dispatch: null

jobs:
  linux-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Build Dependencies
        run: |
          sudo apt-get install puredata -y
          sudo apt-get install python3.11-dev -y
          python3.11 -m pip install numpy
      - name: Build
        run: make PYTHON_VERSION=python3.11
      - name: Copy files to py4pd_Linux
        run: >
          mkdir py4pd_Linux

          cp py4pd.pd_linux test/test.pd resources/py4pd.cfg resources/py.py
          resources/py4pd-help.pd py4pd_Linux

          zip -r py4pd_Linux.zip py4pd_Linux
      
      
      - name: Upload Object
        uses: actions/upload-artifact@v3
        with:
          name: py4pd_Linux
          path: py4pd_Linux.zip
      - name: Set Test Config
        run: >
          cp test/test.py test.py

          python3.11 -m pip install neoscore matplotlib -t
          ./py4pd_Linux/py-modules
      - name: Run Test
        run: python3.11 -c 'import test; test.runTest()'
      - name: Upload Test Image
        uses: actions/upload-artifact@v3
        with:
          name: neoscore-Test-linux
          path: py4pd_Linux/neoscoretest.png

