name: macOS (Intel)
on:
  push:
    branches: [ "master" , "v-0.5.0" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:  
  macos-intel-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install PureData
      run: brew install --cask pd

    - name: Build
      run: make PYTHON_VERSION=python3.11 

    - name: Create py4pd_macOS-Intel
      run: mkdir py4pd_macOS-Intel

    - name: Copy files to py4pd_macOS-Intel
      run: cp py4pd.pd_darwin test/test.pd resources/py4pd.cfg resources/py.py resources/py4pd-help.pd py4pd_macOS-Intel

    - name: Zip py4pd_macOS-Intel
      run: zip -r py4pd_macOS-Intel.zip py4pd_macOS-Intel

    - name: Upload Object
      uses: actions/upload-artifact@v3
      with:
        name: py4pd_macOS-Intel
        path: py4pd_macOS-Intel.zip

    - name: Set Test Config
      run: |
          cp test/test.py test.py
          python3.11 -m pip install neoscore -t ./py4pd_macOS-Intel/py-modules

    - name: Run Test
      run: python3.11 -c 'import test; test.runTest()' 

    - name: Upload Test Image
      uses: actions/upload-artifact@v3
      with:
        name: neoscore-Test-Mac
        path: py4pd_macOS-Intel/neoscoretest.png



    
